spring:
  application:
    name: notification-service
  datasource:
    url: ${NOTIFICATION_DB_URL:jdbc:postgresql://localhost:5433/smartbus_notification}
    username: ${NOTIFICATION_DB_USERNAME:smartbus}
    password: ${NOTIFICATION_DB_PASSWORD:smartbus}
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      connection-timeout: 20000
      idle-timeout: 300000
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    baseline-on-migrate: true
    baseline-version: 0
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
  data:
    mongodb:
      auto-index-creation: false
      repositories:
        type: none
  mongodb:
    uri: ${MONGODB_URI:mongodb://localhost:27017/smartbus_notifications}

server:
  port: ${SERVER_PORT:8084}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

logging:
  pattern:
    console: "%d{yyyy-MM-dd'T'HH:mm:ss.SSS} %-5level [%X{requestId:--}] [%X{bookingReference:--}] %logger{35} - %msg%n"

info:
  app:
    name: SmartBus Notification Service
    phase: foundation

smartbus:
  messaging:
    booking-confirmed-topic: ${BOOKING_CONFIRMED_TOPIC:smartbus.booking.confirmed.v1}
    booking-consumer-group: ${BOOKING_CONSUMER_GROUP:notification-service}
  mongodb:
    enabled: ${SMARTBUS_MONGODB_ENABLED:false}
