-- Schedule service initial schema

create table if not exists schedule_locations (
  id         bigint generated by default as identity  primary key,
  name       varchar(200)              not null unique,
  created_at timestamp with time zone  not null default current_timestamp,
  updated_at timestamp with time zone  not null default current_timestamp
);

create table if not exists schedule_routes (
  route_code       varchar(64)               primary key,
  from_location_id bigint                    not null references schedule_locations(id),
  to_location_id   bigint                    not null references schedule_locations(id),
  departure_time   varchar(64)               not null,
  arrival_time     varchar(64)               not null,
  unit_price       double precision          not null,
  seats_available  integer                   not null,
  created_at       timestamp with time zone  not null default current_timestamp,
  updated_at       timestamp with time zone  not null default current_timestamp
);

create index if not exists idx_schedule_routes_from_location
  on schedule_routes (from_location_id);

create index if not exists idx_schedule_routes_to_location
  on schedule_routes (to_location_id);
